trigger:
- main-v10

pool:
  vmImage: 'windows-latest'

variables:
  projectName: 'Umbraco.Cms.Integrations.OAuthProxy'
  project: 'src/$(projectName)/$(projectName).csproj'
  buildConfiguration: 'Release'
  azureServiceConnectionDev: 'Umbraco Forms Integrations - Umbraco Cloud Services Dev - Hubspot Auth'
  azureServiceConnectionLive: 'Umbraco Forms Integrations - Umbraco Cloud Services Live - Hubspot Auth'
  webAppNameDev: 'azapp-forms-hubspot-auth-we-dev-svc'
  webAppNameLive: 'azapp-forms-hubspot-auth-we-live-svc'

steps:
- script: dotnet build $(project) --configuration $(buildConfiguration)
  displayName: 'Buid Web App'
- task: DotNetCoreCLI@2
  displayName: 'Publish Web App'
  inputs:
    command: 'publish'
    projects: $(project)
    publishWebProjects: false
- task: AzureWebApp@1
  displayName: 'Deploy Web App (Dev)'
  inputs:
    azureSubscription: $(azureServiceConnectionDev)
    appName: $(webAppNameDev)
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
- task: AzureAppServiceSettings@1
  displayName: 'Set Web App Settings (Dev)'
  inputs:
    azureSubscription: $(azureServiceConnectionDev)
    appName: $(webAppNameDev)
    appSettings: |
      [
        {
          "name": "AppSettings:HubspotClientSecret",
          "value": "$(hubSpotAppSecretKey)",
          "slotSetting": false
        },
        {
          "name": "AppSettings:HubspotFormsClientSecret",
          "value": "$(hubSpotAppSecretKey)",
          "slotSetting": false
        },
        {
          "name": "AppSettings:SemrushClientSecret",
          "value": "$(semrushAppSecretKey)",
          "slotSetting": false
        },
        {
          "name": "AppSettings:GoogleClientSecret",
          "value": "$(googleAppSecretKey)",
          "slotSetting": false
        },
        {
          "name": "AppSettings:DynamicsClientSecret",
          "value": "$(dynamicsAppSecretKey)",
          "slotSetting": false
        },
        {
          "name": "AppSettings:ShopifyClientSecret",
          "value": "$(shopifyAppSecretKey)",
          "slotSetting": false
        },
        {
          "name": "AppSettings:ShopifyClientId",
          "value": "$(shopifyAppClientIdKey)",
          "slotSetting": false
        }
      ]
- task: AzureWebApp@1
  displayName: 'Deploy Web App (Live)'
  inputs:
    azureSubscription: $(azureServiceConnectionLive)
    appName: $(webAppNameLive)
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
- task: AzureAppServiceSettings@1
  displayName: 'Set Web App Settings (Live)'
  inputs:
    azureSubscription: $(azureServiceConnectionLive)
    appName: $(webAppNameLive)
    appSettings: |
      [
        {
          "name": "AppSettings:HubspotClientSecret",
          "value": "$(hubSpotAppSecretKey)",
          "slotSetting": false
        },
        {
          "name": "AppSettings:HubspotFormsClientSecret",
          "value": "$(hubSpotAppSecretKey)",
          "slotSetting": false
        },
        {
          "name": "AppSettings:SemrushClientSecret",
          "value": "$(semrushAppSecretKey)",
          "slotSetting": false
        },
        {
          "name": "AppSettings:GoogleClientSecret",
          "value": "$(googleAppSecretKey)",
          "slotSetting": false
        },
        {
          "name": "AppSettings:DynamicsClientSecret",
          "value": "$(dynamicsAppSecretKey)",
          "slotSetting": false
        },
        {
          "name": "AppSettings:ShopifyClientSecret",
          "value": "$(shopifyAppSecretKey)",
          "slotSetting": false
        },
        {
          "name": "AppSettings:ShopifyClientId",
          "value": "$(shopifyAppClientIdKey)",
          "slotSetting": false
        }
      ]